// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.4
// source: trade/trade.proto

// Package trade defines the fields of data types which shared
// between services.

package trade

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A Quote represents the daily trading data of a Security on
// a specific date.
type Quote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Date  string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // date in format "YYYY-MM-DD"
	Open  float64                `protobuf:"fixed64,2,opt,name=open,proto3" json:"open,omitempty"`
	High  float64                `protobuf:"fixed64,3,opt,name=high,proto3" json:"high,omitempty"`
	Low   float64                `protobuf:"fixed64,4,opt,name=low,proto3" json:"low,omitempty"`
	Close float64                `protobuf:"fixed64,5,opt,name=close,proto3" json:"close,omitempty"`
	// -1: halted
	Volume        uint64  `protobuf:"varint,6,opt,name=volume,proto3" json:"volume,omitempty"`
	Avg           float64 `protobuf:"fixed64,7,opt,name=avg,proto3" json:"avg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quote) Reset() {
	*x = Quote{}
	mi := &file_trade_trade_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quote) ProtoMessage() {}

func (x *Quote) ProtoReflect() protoreflect.Message {
	mi := &file_trade_trade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quote.ProtoReflect.Descriptor instead.
func (*Quote) Descriptor() ([]byte, []int) {
	return file_trade_trade_proto_rawDescGZIP(), []int{0}
}

func (x *Quote) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Quote) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Quote) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Quote) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Quote) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Quote) GetVolume() uint64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Quote) GetAvg() float64 {
	if x != nil {
		return x.Avg
	}
	return 0
}

// A Security represents a financial instrument in a Market.
type Security struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        string                 `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Isin          string                 `protobuf:"bytes,2,opt,name=isin,proto3" json:"isin,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Listed        string                 `protobuf:"bytes,6,opt,name=listed,proto3" json:"listed,omitempty"`     // date in format "YYYY-MM-DD"
	Delisted      string                 `protobuf:"bytes,7,opt,name=delisted,proto3" json:"delisted,omitempty"` // date in format "YYYY-MM-DD"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Security) Reset() {
	*x = Security{}
	mi := &file_trade_trade_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security) ProtoMessage() {}

func (x *Security) ProtoReflect() protoreflect.Message {
	mi := &file_trade_trade_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Security.ProtoReflect.Descriptor instead.
func (*Security) Descriptor() ([]byte, []int) {
	return file_trade_trade_proto_rawDescGZIP(), []int{1}
}

func (x *Security) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *Security) GetIsin() string {
	if x != nil {
		return x.Isin
	}
	return ""
}

func (x *Security) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Security) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Security) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Security) GetListed() string {
	if x != nil {
		return x.Listed
	}
	return ""
}

func (x *Security) GetDelisted() string {
	if x != nil {
		return x.Delisted
	}
	return ""
}

// A Market represents an exchange where financial instruments
// are traded.
type Market struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Market) Reset() {
	*x = Market{}
	mi := &file_trade_trade_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Market) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Market) ProtoMessage() {}

func (x *Market) ProtoReflect() protoreflect.Message {
	mi := &file_trade_trade_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Market.ProtoReflect.Descriptor instead.
func (*Market) Descriptor() ([]byte, []int) {
	return file_trade_trade_proto_rawDescGZIP(), []int{2}
}

func (x *Market) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Market) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Market) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_trade_trade_proto protoreflect.FileDescriptor

const file_trade_trade_proto_rawDesc = "" +
	"\n" +
	"\x11trade/trade.proto\x12\x05trade\"\x95\x01\n" +
	"\x05Quote\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x12\n" +
	"\x04open\x18\x02 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x03 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x04 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\x05 \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\x04R\x06volume\x12\x10\n" +
	"\x03avg\x18\a \x01(\x01R\x03avg\"\xaa\x01\n" +
	"\bSecurity\x12\x16\n" +
	"\x06market\x18\x01 \x01(\tR\x06market\x12\x12\n" +
	"\x04isin\x18\x02 \x01(\tR\x04isin\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x16\n" +
	"\x06listed\x18\x06 \x01(\tR\x06listed\x12\x1a\n" +
	"\bdelisted\x18\a \x01(\tR\bdelisted\"L\n" +
	"\x06Market\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrencyB!Z\x1fgithub.com/Hunsin/compass/tradeb\x06proto3"

var (
	file_trade_trade_proto_rawDescOnce sync.Once
	file_trade_trade_proto_rawDescData []byte
)

func file_trade_trade_proto_rawDescGZIP() []byte {
	file_trade_trade_proto_rawDescOnce.Do(func() {
		file_trade_trade_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trade_trade_proto_rawDesc), len(file_trade_trade_proto_rawDesc)))
	})
	return file_trade_trade_proto_rawDescData
}

var file_trade_trade_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_trade_trade_proto_goTypes = []any{
	(*Quote)(nil),    // 0: trade.Quote
	(*Security)(nil), // 1: trade.Security
	(*Market)(nil),   // 2: trade.Market
}
var file_trade_trade_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trade_trade_proto_init() }
func file_trade_trade_proto_init() {
	if File_trade_trade_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trade_trade_proto_rawDesc), len(file_trade_trade_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trade_trade_proto_goTypes,
		DependencyIndexes: file_trade_trade_proto_depIdxs,
		MessageInfos:      file_trade_trade_proto_msgTypes,
	}.Build()
	File_trade_trade_proto = out.File
	file_trade_trade_proto_goTypes = nil
	file_trade_trade_proto_depIdxs = nil
}
