// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/Hunsin/compass/trade/trade.proto

package trade

/*
Package trade defines the fields of data types which shared
between services.
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A Quote represents the daily trading data of a Security on
// a specific date.
type Quote struct {
	Date  string  `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Open  float64 `protobuf:"fixed64,2,opt,name=open,proto3" json:"open,omitempty"`
	High  float64 `protobuf:"fixed64,3,opt,name=high,proto3" json:"high,omitempty"`
	Low   float64 `protobuf:"fixed64,4,opt,name=low,proto3" json:"low,omitempty"`
	Close float64 `protobuf:"fixed64,5,opt,name=close,proto3" json:"close,omitempty"`
	// -1: halted
	Volume               uint64   `protobuf:"varint,6,opt,name=volume,proto3" json:"volume,omitempty"`
	Avg                  float64  `protobuf:"fixed64,7,opt,name=avg,proto3" json:"avg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Quote) Reset()         { *m = Quote{} }
func (m *Quote) String() string { return proto.CompactTextString(m) }
func (*Quote) ProtoMessage()    {}
func (*Quote) Descriptor() ([]byte, []int) {
	return fileDescriptor_trade_32a1eb35178e818a, []int{0}
}
func (m *Quote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quote.Unmarshal(m, b)
}
func (m *Quote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quote.Marshal(b, m, deterministic)
}
func (dst *Quote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quote.Merge(dst, src)
}
func (m *Quote) XXX_Size() int {
	return xxx_messageInfo_Quote.Size(m)
}
func (m *Quote) XXX_DiscardUnknown() {
	xxx_messageInfo_Quote.DiscardUnknown(m)
}

var xxx_messageInfo_Quote proto.InternalMessageInfo

func (m *Quote) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Quote) GetOpen() float64 {
	if m != nil {
		return m.Open
	}
	return 0
}

func (m *Quote) GetHigh() float64 {
	if m != nil {
		return m.High
	}
	return 0
}

func (m *Quote) GetLow() float64 {
	if m != nil {
		return m.Low
	}
	return 0
}

func (m *Quote) GetClose() float64 {
	if m != nil {
		return m.Close
	}
	return 0
}

func (m *Quote) GetVolume() uint64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *Quote) GetAvg() float64 {
	if m != nil {
		return m.Avg
	}
	return 0
}

// A Security represents a financial instrument in a Market.
type Security struct {
	Market               string   `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Isin                 string   `protobuf:"bytes,2,opt,name=isin,proto3" json:"isin,omitempty"`
	Symbol               string   `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Listed               string   `protobuf:"bytes,6,opt,name=listed,proto3" json:"listed,omitempty"`
	Delisted             string   `protobuf:"bytes,7,opt,name=delisted,proto3" json:"delisted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Security) Reset()         { *m = Security{} }
func (m *Security) String() string { return proto.CompactTextString(m) }
func (*Security) ProtoMessage()    {}
func (*Security) Descriptor() ([]byte, []int) {
	return fileDescriptor_trade_32a1eb35178e818a, []int{1}
}
func (m *Security) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Security.Unmarshal(m, b)
}
func (m *Security) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Security.Marshal(b, m, deterministic)
}
func (dst *Security) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Security.Merge(dst, src)
}
func (m *Security) XXX_Size() int {
	return xxx_messageInfo_Security.Size(m)
}
func (m *Security) XXX_DiscardUnknown() {
	xxx_messageInfo_Security.DiscardUnknown(m)
}

var xxx_messageInfo_Security proto.InternalMessageInfo

func (m *Security) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *Security) GetIsin() string {
	if m != nil {
		return m.Isin
	}
	return ""
}

func (m *Security) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Security) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Security) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Security) GetListed() string {
	if m != nil {
		return m.Listed
	}
	return ""
}

func (m *Security) GetDelisted() string {
	if m != nil {
		return m.Delisted
	}
	return ""
}

// A Market represents an exchange where financial instruments
// are traded.
type Market struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Currency             string   `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Market) Reset()         { *m = Market{} }
func (m *Market) String() string { return proto.CompactTextString(m) }
func (*Market) ProtoMessage()    {}
func (*Market) Descriptor() ([]byte, []int) {
	return fileDescriptor_trade_32a1eb35178e818a, []int{2}
}
func (m *Market) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Market.Unmarshal(m, b)
}
func (m *Market) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Market.Marshal(b, m, deterministic)
}
func (dst *Market) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Market.Merge(dst, src)
}
func (m *Market) XXX_Size() int {
	return xxx_messageInfo_Market.Size(m)
}
func (m *Market) XXX_DiscardUnknown() {
	xxx_messageInfo_Market.DiscardUnknown(m)
}

var xxx_messageInfo_Market proto.InternalMessageInfo

func (m *Market) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Market) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Market) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func init() {
	proto.RegisterType((*Quote)(nil), "trade.Quote")
	proto.RegisterType((*Security)(nil), "trade.Security")
	proto.RegisterType((*Market)(nil), "trade.Market")
}

func init() {
	proto.RegisterFile("github.com/Hunsin/compass/trade/trade.proto", fileDescriptor_trade_32a1eb35178e818a)
}

var fileDescriptor_trade_32a1eb35178e818a = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x4d, 0x6a, 0xc3, 0x30,
	0x10, 0x85, 0x51, 0x12, 0x3b, 0xb1, 0x56, 0x45, 0x94, 0x22, 0xb2, 0x0a, 0x59, 0x05, 0x0a, 0xc9,
	0xa2, 0x97, 0xe8, 0xa2, 0x5d, 0x54, 0x3d, 0x81, 0x22, 0x0f, 0x8e, 0xa8, 0x6d, 0x19, 0xfd, 0xa4,
	0xf8, 0x20, 0xbd, 0x44, 0x4f, 0x59, 0x66, 0x24, 0x4c, 0x37, 0xe6, 0x7d, 0x4f, 0x1a, 0xe6, 0xc3,
	0xe2, 0xcf, 0x9d, 0x8d, 0xb7, 0x74, 0x3d, 0x1b, 0x37, 0x5c, 0x5e, 0xd3, 0x18, 0xec, 0x78, 0x31,
	0x6e, 0x98, 0x74, 0x08, 0x97, 0xe8, 0x75, 0x0b, 0xf9, 0x7b, 0x9e, 0xbc, 0x8b, 0x4e, 0x54, 0x04,
	0xc7, 0x1f, 0xc6, 0xab, 0x8f, 0xe4, 0x22, 0x08, 0xc1, 0x37, 0xad, 0x8e, 0x20, 0xd9, 0x81, 0x9d,
	0x1a, 0x45, 0x19, 0x3b, 0x37, 0xc1, 0x28, 0x57, 0x07, 0x76, 0x62, 0x8a, 0x32, 0x76, 0x37, 0xdb,
	0xdd, 0xe4, 0x3a, 0x77, 0x98, 0xc5, 0x03, 0x5f, 0xf7, 0xee, 0x5b, 0x6e, 0xa8, 0xc2, 0x28, 0x1e,
	0x79, 0x65, 0x7a, 0x17, 0x40, 0x56, 0xd4, 0x65, 0x10, 0x4f, 0xbc, 0xbe, 0xbb, 0x3e, 0x0d, 0x20,
	0xeb, 0x03, 0x3b, 0x6d, 0x54, 0x21, 0x9c, 0xd7, 0xf7, 0x4e, 0x6e, 0xf3, 0xbc, 0xbe, 0x77, 0xc7,
	0x5f, 0xc6, 0x77, 0x9f, 0x60, 0x92, 0xb7, 0x71, 0xc6, 0xb1, 0x41, 0xfb, 0x2f, 0x88, 0x45, 0xae,
	0x10, 0xaa, 0xd8, 0x60, 0xb3, 0x5e, 0xa3, 0x28, 0xe3, 0xdd, 0x30, 0x0f, 0x57, 0xd7, 0x93, 0x60,
	0xa3, 0x0a, 0xe1, 0xdd, 0x51, 0x0f, 0x40, 0x8e, 0x8d, 0xa2, 0x8c, 0x5d, 0x9c, 0xa7, 0xec, 0xd8,
	0x28, 0xca, 0x38, 0xdf, 0xdb, 0x10, 0xa1, 0x25, 0xc5, 0x46, 0x15, 0x12, 0x7b, 0xbe, 0x6b, 0xa1,
	0x9c, 0x6c, 0xe9, 0x64, 0xe1, 0xe3, 0x1b, 0xaf, 0xdf, 0x17, 0x23, 0xe3, 0xda, 0xe5, 0x27, 0x62,
	0x5e, 0x36, 0xaf, 0xfe, 0x6d, 0xde, 0xf3, 0x9d, 0x49, 0xde, 0xc3, 0x68, 0xe6, 0xe2, 0xb9, 0xf0,
	0xb5, 0xa6, 0x07, 0x7a, 0xf9, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x2e, 0xa9, 0xf6, 0x0e, 0xcf, 0x01,
	0x00, 0x00,
}
