language: go
  
go:
  - 1.8.x
  - 1.9.x
  - 1.10.x

sudo: required

services: postgresql

before_script:
  - psql -c 'create database compass;' -U postgres

script:
  - go test -v github.com/Hunsin/compass/crawler -user postgres -db compass
  - go test -v github.com/Hunsin/compass/twse
  - go test -v github.com/Hunsin/compass/bucket -user postgres -db compass
