language: go
  
go:
  - 1.8
  - 1.9

sudo: required

services: postgresql

before_install: export GOPATH=$TRAVIS_BUILD_DIR

before_script:
  - psql -c 'create database bucket;' -U postgres
  - psql -c 'create role $USER superuser;' -U postgres

script:
  - go test -v twse
  - go test -v bucket
