language: go
  
go:
  - 1.8
  - 1.9

sudo: required

services: postgresql

before_script:
  - psql -c 'create database compass;' -U postgres

script:
  - go test -v github.com/Hunsin/compass/crawler -user postgres -db compass
  - go test -v github.com/Hunsin/compass/twse
  - go test -v github.com/Hunsin/compass/bucket -user postgres -db compass
