language: go
  
go:
  - 1.8
  - 1.9

sudo: required

before_install: export GOPATH=$TRAVIS_BUILD_DIR

install:
  - go get golang.org/x/text/transform
  - go get golang.org/x/text/encoding/traditionalchinese

script: go test -v twse
