x-tools-shared: &tools-shared
  volumes:
    - ${ROOT_DIR:?error}:/compass
  working_dir: /compass
  networks:
    - compass
  profiles:
    - tools

services:
  dev:
    <<: *tools-shared
    build:
      dockerfile: dockerfiles/dev.Dockerfile
      tags:
        - compass/dev:${GIT_COMMIT_SHA:?error}
    image: compass/dev:${GIT_COMMIT_SHA:?error}
    environment:
      - ROOT_DIR=${ROOT_DIR:?error}
    env_file:
      - .env
    volumes:
      - ${ROOT_DIR:?error}:/compass
      - /var/run/docker.sock:/var/run/docker.sock

  migrate:
    <<: *tools-shared
    image: migrate/migrate:v4.19.1
    entrypoint:
      - migrate
      - -path=postgres/migrations
      - -database=${POSTGRES_URL}

  sqlc:
    <<: *tools-shared
    image: sqlc/sqlc:1.30.0
    command: generate
    env_file:
      - .env

  buf:
    <<: *tools-shared
    image: bufbuild/buf:1.65.0
    command: generate

  mockery:
    <<: *tools-shared
    image: vektra/mockery:v3.7.0

  postgres:
    image: postgres:18.2-alpine3.23
    container_name: compass-postgres
    env_file:
      - .env
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - compass

  redis:
    image: redis:8.6.1-alpine3.23
    container_name: compass-redis
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - compass

  app:
    build:
      dockerfile: dockerfiles/app.Dockerfile
      tags:
        - compass/app:${GIT_COMMIT_SHA:?error}
    image: compass/app:${GIT_COMMIT_SHA:?error}
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - compass
    profiles:
      - app

  keycloak-postgres:
    image: postgres:18.2-alpine3.23
    container_name: compass-keycloak-postgres
    environment:
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      POSTGRES_DB: ${KEYCLOAK_DB}
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - compass

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: compass-keycloak
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://compass-keycloak-postgres:5432/${KEYCLOAK_DB}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    ports:
      - "8180:8080"
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    networks:
      - compass

networks:
  compass:
    name: compass
