#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "${POSTGRES_DB:-$POSTGRES_USER}" <<-EOSQL
	CREATE USER $KEYCLOAK_DB_USER WITH ENCRYPTED PASSWORD '$KEYCLOAK_DB_PASSWORD';
	CREATE DATABASE $KEYCLOAK_DB;
	GRANT ALL PRIVILEGES ON DATABASE $KEYCLOAK_DB TO $KEYCLOAK_DB_USER;
	\c $KEYCLOAK_DB
	GRANT ALL ON SCHEMA public TO $KEYCLOAK_DB_USER;
EOSQL
