// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/Hunsin/compass/pb/APIs.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	github.com/Hunsin/compass/pb/APIs.proto

It has these top-level messages:
	Filter
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import trade "github.com/Hunsin/compass/trade"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Filter struct {
	Symbol string `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	After  string `protobuf:"bytes,2,opt,name=after" json:"after,omitempty"`
	Before string `protobuf:"bytes,3,opt,name=before" json:"before,omitempty"`
	Type   string `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
}

func (m *Filter) Reset()                    { *m = Filter{} }
func (m *Filter) String() string            { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()               {}
func (*Filter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Filter) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Filter) GetAfter() string {
	if m != nil {
		return m.After
	}
	return ""
}

func (m *Filter) GetBefore() string {
	if m != nil {
		return m.Before
	}
	return ""
}

func (m *Filter) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func init() {
	proto.RegisterType((*Filter)(nil), "pb.Filter")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Predator service

type PredatorClient interface {
	Markets(ctx context.Context, in *trade.Null, opts ...grpc.CallOption) (Predator_MarketsClient, error)
	Securities(ctx context.Context, in *Filter, opts ...grpc.CallOption) (Predator_SecuritiesClient, error)
	Records(ctx context.Context, in *Filter, opts ...grpc.CallOption) (Predator_RecordsClient, error)
}

type predatorClient struct {
	cc *grpc.ClientConn
}

func NewPredatorClient(cc *grpc.ClientConn) PredatorClient {
	return &predatorClient{cc}
}

func (c *predatorClient) Markets(ctx context.Context, in *trade.Null, opts ...grpc.CallOption) (Predator_MarketsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Predator_serviceDesc.Streams[0], c.cc, "/pb.Predator/Markets", opts...)
	if err != nil {
		return nil, err
	}
	x := &predatorMarketsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Predator_MarketsClient interface {
	Recv() (*trade.Market, error)
	grpc.ClientStream
}

type predatorMarketsClient struct {
	grpc.ClientStream
}

func (x *predatorMarketsClient) Recv() (*trade.Market, error) {
	m := new(trade.Market)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *predatorClient) Securities(ctx context.Context, in *Filter, opts ...grpc.CallOption) (Predator_SecuritiesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Predator_serviceDesc.Streams[1], c.cc, "/pb.Predator/Securities", opts...)
	if err != nil {
		return nil, err
	}
	x := &predatorSecuritiesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Predator_SecuritiesClient interface {
	Recv() (*trade.Security, error)
	grpc.ClientStream
}

type predatorSecuritiesClient struct {
	grpc.ClientStream
}

func (x *predatorSecuritiesClient) Recv() (*trade.Security, error) {
	m := new(trade.Security)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *predatorClient) Records(ctx context.Context, in *Filter, opts ...grpc.CallOption) (Predator_RecordsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Predator_serviceDesc.Streams[2], c.cc, "/pb.Predator/Records", opts...)
	if err != nil {
		return nil, err
	}
	x := &predatorRecordsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Predator_RecordsClient interface {
	Recv() (*trade.Daily, error)
	grpc.ClientStream
}

type predatorRecordsClient struct {
	grpc.ClientStream
}

func (x *predatorRecordsClient) Recv() (*trade.Daily, error) {
	m := new(trade.Daily)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Predator service

type PredatorServer interface {
	Markets(*trade.Null, Predator_MarketsServer) error
	Securities(*Filter, Predator_SecuritiesServer) error
	Records(*Filter, Predator_RecordsServer) error
}

func RegisterPredatorServer(s *grpc.Server, srv PredatorServer) {
	s.RegisterService(&_Predator_serviceDesc, srv)
}

func _Predator_Markets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(trade.Null)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PredatorServer).Markets(m, &predatorMarketsServer{stream})
}

type Predator_MarketsServer interface {
	Send(*trade.Market) error
	grpc.ServerStream
}

type predatorMarketsServer struct {
	grpc.ServerStream
}

func (x *predatorMarketsServer) Send(m *trade.Market) error {
	return x.ServerStream.SendMsg(m)
}

func _Predator_Securities_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Filter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PredatorServer).Securities(m, &predatorSecuritiesServer{stream})
}

type Predator_SecuritiesServer interface {
	Send(*trade.Security) error
	grpc.ServerStream
}

type predatorSecuritiesServer struct {
	grpc.ServerStream
}

func (x *predatorSecuritiesServer) Send(m *trade.Security) error {
	return x.ServerStream.SendMsg(m)
}

func _Predator_Records_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Filter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PredatorServer).Records(m, &predatorRecordsServer{stream})
}

type Predator_RecordsServer interface {
	Send(*trade.Daily) error
	grpc.ServerStream
}

type predatorRecordsServer struct {
	grpc.ServerStream
}

func (x *predatorRecordsServer) Send(m *trade.Daily) error {
	return x.ServerStream.SendMsg(m)
}

var _Predator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Predator",
	HandlerType: (*PredatorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Markets",
			Handler:       _Predator_Markets_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Securities",
			Handler:       _Predator_Securities_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Records",
			Handler:       _Predator_Records_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "github.com/Hunsin/compass/pb/APIs.proto",
}

func init() { proto.RegisterFile("github.com/Hunsin/compass/pb/APIs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0xc1, 0x4a, 0xc4, 0x30,
	0x14, 0x45, 0xc9, 0x38, 0x76, 0xf4, 0xa9, 0x08, 0x0f, 0x91, 0xd2, 0x95, 0x08, 0x32, 0xc2, 0x40,
	0x5a, 0xf4, 0x0b, 0x04, 0x11, 0x5d, 0x28, 0xc3, 0xf8, 0x05, 0x49, 0xfb, 0x46, 0x83, 0x69, 0x13,
	0x5e, 0xd2, 0x45, 0xbf, 0xc0, 0xdf, 0x16, 0x9b, 0x6c, 0x5c, 0xb8, 0x09, 0x39, 0xf7, 0x9e, 0xc0,
	0x0d, 0xac, 0x3f, 0x4c, 0xfc, 0x1c, 0xb5, 0x6c, 0x5d, 0x5f, 0x3f, 0x8f, 0x43, 0x30, 0x43, 0xdd,
	0xba, 0xde, 0xab, 0x10, 0x6a, 0xaf, 0xeb, 0x87, 0xed, 0x4b, 0x90, 0x9e, 0x5d, 0x74, 0xb8, 0xf0,
	0xba, 0xda, 0xfc, 0x2f, 0x47, 0x56, 0x1d, 0xa5, 0x33, 0x3d, 0xb8, 0xd6, 0x50, 0x3c, 0x19, 0x1b,
	0x89, 0xf1, 0x12, 0x8a, 0x30, 0xf5, 0xda, 0xd9, 0x52, 0x5c, 0x89, 0xdb, 0xe3, 0x5d, 0x26, 0xbc,
	0x80, 0x43, 0xb5, 0x8f, 0xc4, 0xe5, 0x62, 0x8e, 0x13, 0xfc, 0xda, 0x9a, 0xf6, 0x8e, 0xa9, 0x3c,
	0x48, 0x76, 0x22, 0x44, 0x58, 0xc6, 0xc9, 0x53, 0xb9, 0x9c, 0xd3, 0xf9, 0x7e, 0xf7, 0x2d, 0xe0,
	0x68, 0xcb, 0xd4, 0xa9, 0xe8, 0x18, 0xd7, 0xb0, 0x7a, 0x55, 0xfc, 0x45, 0x31, 0xe0, 0x89, 0x4c,
	0x4b, 0xde, 0x46, 0x6b, 0xab, 0xb3, 0x0c, 0xa9, 0x6c, 0x04, 0x6e, 0x00, 0xde, 0xa9, 0x1d, 0xd9,
	0x44, 0x43, 0x01, 0x41, 0x7a, 0x2d, 0xd3, 0xd2, 0xea, 0x3c, 0xab, 0xb9, 0x9e, 0x1a, 0x81, 0x37,
	0xb0, 0xda, 0x51, 0xeb, 0xb8, 0xfb, 0x6b, 0x9e, 0x66, 0xf3, 0x51, 0x19, 0x3b, 0x35, 0x42, 0x17,
	0xf3, 0xa7, 0xef, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x83, 0x5b, 0xd9, 0x50, 0x01, 0x00,
	0x00,
}
