// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: trade/pb/APIs.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Compass_Register_FullMethodName  = "/pb.Compass/Register"
	Compass_Predators_FullMethodName = "/pb.Compass/Predators"
)

// CompassClient is the client API for Compass service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CompassClient interface {
	Register(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Result, Query], error)
	Predators(ctx context.Context, in *Null, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Predator], error)
}

type compassClient struct {
	cc grpc.ClientConnInterface
}

func NewCompassClient(cc grpc.ClientConnInterface) CompassClient {
	return &compassClient{cc}
}

func (c *compassClient) Register(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Result, Query], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Compass_ServiceDesc.Streams[0], Compass_Register_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Result, Query]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Compass_RegisterClient = grpc.BidiStreamingClient[Result, Query]

func (c *compassClient) Predators(ctx context.Context, in *Null, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Predator], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Compass_ServiceDesc.Streams[1], Compass_Predators_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Null, Predator]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Compass_PredatorsClient = grpc.ServerStreamingClient[Predator]

// CompassServer is the server API for Compass service.
// All implementations must embed UnimplementedCompassServer
// for forward compatibility.
type CompassServer interface {
	Register(grpc.BidiStreamingServer[Result, Query]) error
	Predators(*Null, grpc.ServerStreamingServer[Predator]) error
	mustEmbedUnimplementedCompassServer()
}

// UnimplementedCompassServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCompassServer struct{}

func (UnimplementedCompassServer) Register(grpc.BidiStreamingServer[Result, Query]) error {
	return status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedCompassServer) Predators(*Null, grpc.ServerStreamingServer[Predator]) error {
	return status.Errorf(codes.Unimplemented, "method Predators not implemented")
}
func (UnimplementedCompassServer) mustEmbedUnimplementedCompassServer() {}
func (UnimplementedCompassServer) testEmbeddedByValue()                 {}

// UnsafeCompassServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompassServer will
// result in compilation errors.
type UnsafeCompassServer interface {
	mustEmbedUnimplementedCompassServer()
}

func RegisterCompassServer(s grpc.ServiceRegistrar, srv CompassServer) {
	// If the following call pancis, it indicates UnimplementedCompassServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Compass_ServiceDesc, srv)
}

func _Compass_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CompassServer).Register(&grpc.GenericServerStream[Result, Query]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Compass_RegisterServer = grpc.BidiStreamingServer[Result, Query]

func _Compass_Predators_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Null)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CompassServer).Predators(m, &grpc.GenericServerStream[Null, Predator]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Compass_PredatorsServer = grpc.ServerStreamingServer[Predator]

// Compass_ServiceDesc is the grpc.ServiceDesc for Compass service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Compass_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Compass",
	HandlerType: (*CompassServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Register",
			Handler:       _Compass_Register_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Predators",
			Handler:       _Compass_Predators_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "trade/pb/APIs.proto",
}
