// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/Hunsin/compass/trade/pb/APIs.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	github.com/Hunsin/compass/trade/pb/APIs.proto

It has these top-level messages:
	Filter
	Crawler
	Null
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import trade "github.com/Hunsin/compass/trade"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Filter struct {
	Symbol   string `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	FromDate string `protobuf:"bytes,2,opt,name=from_date,json=fromDate" json:"from_date,omitempty"`
	EndDate  string `protobuf:"bytes,3,opt,name=end_date,json=endDate" json:"end_date,omitempty"`
	Type     string `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
}

func (m *Filter) Reset()                    { *m = Filter{} }
func (m *Filter) String() string            { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()               {}
func (*Filter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Filter) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Filter) GetFromDate() string {
	if m != nil {
		return m.FromDate
	}
	return ""
}

func (m *Filter) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *Filter) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Crawler struct {
	Id  string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Url string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
}

func (m *Crawler) Reset()                    { *m = Crawler{} }
func (m *Crawler) String() string            { return proto.CompactTextString(m) }
func (*Crawler) ProtoMessage()               {}
func (*Crawler) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Crawler) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Crawler) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// A Null is nothing.
type Null struct {
}

func (m *Null) Reset()                    { *m = Null{} }
func (m *Null) String() string            { return proto.CompactTextString(m) }
func (*Null) ProtoMessage()               {}
func (*Null) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Filter)(nil), "pb.Filter")
	proto.RegisterType((*Crawler)(nil), "pb.Crawler")
	proto.RegisterType((*Null)(nil), "pb.Null")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Compass service

type CompassClient interface {
	Register(ctx context.Context, in *Crawler, opts ...grpc.CallOption) (*Null, error)
	Crawlers(ctx context.Context, in *Null, opts ...grpc.CallOption) (Compass_CrawlersClient, error)
}

type compassClient struct {
	cc *grpc.ClientConn
}

func NewCompassClient(cc *grpc.ClientConn) CompassClient {
	return &compassClient{cc}
}

func (c *compassClient) Register(ctx context.Context, in *Crawler, opts ...grpc.CallOption) (*Null, error) {
	out := new(Null)
	err := grpc.Invoke(ctx, "/pb.Compass/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compassClient) Crawlers(ctx context.Context, in *Null, opts ...grpc.CallOption) (Compass_CrawlersClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Compass_serviceDesc.Streams[0], c.cc, "/pb.Compass/Crawlers", opts...)
	if err != nil {
		return nil, err
	}
	x := &compassCrawlersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Compass_CrawlersClient interface {
	Recv() (*Crawler, error)
	grpc.ClientStream
}

type compassCrawlersClient struct {
	grpc.ClientStream
}

func (x *compassCrawlersClient) Recv() (*Crawler, error) {
	m := new(Crawler)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Compass service

type CompassServer interface {
	Register(context.Context, *Crawler) (*Null, error)
	Crawlers(*Null, Compass_CrawlersServer) error
}

func RegisterCompassServer(s *grpc.Server, srv CompassServer) {
	s.RegisterService(&_Compass_serviceDesc, srv)
}

func _Compass_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Crawler)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompassServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Compass/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompassServer).Register(ctx, req.(*Crawler))
	}
	return interceptor(ctx, in, info, handler)
}

func _Compass_Crawlers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Null)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CompassServer).Crawlers(m, &compassCrawlersServer{stream})
}

type Compass_CrawlersServer interface {
	Send(*Crawler) error
	grpc.ServerStream
}

type compassCrawlersServer struct {
	grpc.ServerStream
}

func (x *compassCrawlersServer) Send(m *Crawler) error {
	return x.ServerStream.SendMsg(m)
}

var _Compass_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Compass",
	HandlerType: (*CompassServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Compass_Register_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Crawlers",
			Handler:       _Compass_Crawlers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "github.com/Hunsin/compass/trade/pb/APIs.proto",
}

// Client API for Predator service

type PredatorClient interface {
	Markets(ctx context.Context, in *Null, opts ...grpc.CallOption) (Predator_MarketsClient, error)
	Securities(ctx context.Context, in *Filter, opts ...grpc.CallOption) (Predator_SecuritiesClient, error)
	Records(ctx context.Context, in *Filter, opts ...grpc.CallOption) (Predator_RecordsClient, error)
}

type predatorClient struct {
	cc *grpc.ClientConn
}

func NewPredatorClient(cc *grpc.ClientConn) PredatorClient {
	return &predatorClient{cc}
}

func (c *predatorClient) Markets(ctx context.Context, in *Null, opts ...grpc.CallOption) (Predator_MarketsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Predator_serviceDesc.Streams[0], c.cc, "/pb.Predator/Markets", opts...)
	if err != nil {
		return nil, err
	}
	x := &predatorMarketsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Predator_MarketsClient interface {
	Recv() (*trade.Market, error)
	grpc.ClientStream
}

type predatorMarketsClient struct {
	grpc.ClientStream
}

func (x *predatorMarketsClient) Recv() (*trade.Market, error) {
	m := new(trade.Market)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *predatorClient) Securities(ctx context.Context, in *Filter, opts ...grpc.CallOption) (Predator_SecuritiesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Predator_serviceDesc.Streams[1], c.cc, "/pb.Predator/Securities", opts...)
	if err != nil {
		return nil, err
	}
	x := &predatorSecuritiesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Predator_SecuritiesClient interface {
	Recv() (*trade.Security, error)
	grpc.ClientStream
}

type predatorSecuritiesClient struct {
	grpc.ClientStream
}

func (x *predatorSecuritiesClient) Recv() (*trade.Security, error) {
	m := new(trade.Security)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *predatorClient) Records(ctx context.Context, in *Filter, opts ...grpc.CallOption) (Predator_RecordsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Predator_serviceDesc.Streams[2], c.cc, "/pb.Predator/Records", opts...)
	if err != nil {
		return nil, err
	}
	x := &predatorRecordsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Predator_RecordsClient interface {
	Recv() (*trade.Daily, error)
	grpc.ClientStream
}

type predatorRecordsClient struct {
	grpc.ClientStream
}

func (x *predatorRecordsClient) Recv() (*trade.Daily, error) {
	m := new(trade.Daily)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Predator service

type PredatorServer interface {
	Markets(*Null, Predator_MarketsServer) error
	Securities(*Filter, Predator_SecuritiesServer) error
	Records(*Filter, Predator_RecordsServer) error
}

func RegisterPredatorServer(s *grpc.Server, srv PredatorServer) {
	s.RegisterService(&_Predator_serviceDesc, srv)
}

func _Predator_Markets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Null)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PredatorServer).Markets(m, &predatorMarketsServer{stream})
}

type Predator_MarketsServer interface {
	Send(*trade.Market) error
	grpc.ServerStream
}

type predatorMarketsServer struct {
	grpc.ServerStream
}

func (x *predatorMarketsServer) Send(m *trade.Market) error {
	return x.ServerStream.SendMsg(m)
}

func _Predator_Securities_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Filter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PredatorServer).Securities(m, &predatorSecuritiesServer{stream})
}

type Predator_SecuritiesServer interface {
	Send(*trade.Security) error
	grpc.ServerStream
}

type predatorSecuritiesServer struct {
	grpc.ServerStream
}

func (x *predatorSecuritiesServer) Send(m *trade.Security) error {
	return x.ServerStream.SendMsg(m)
}

func _Predator_Records_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Filter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PredatorServer).Records(m, &predatorRecordsServer{stream})
}

type Predator_RecordsServer interface {
	Send(*trade.Daily) error
	grpc.ServerStream
}

type predatorRecordsServer struct {
	grpc.ServerStream
}

func (x *predatorRecordsServer) Send(m *trade.Daily) error {
	return x.ServerStream.SendMsg(m)
}

var _Predator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Predator",
	HandlerType: (*PredatorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Markets",
			Handler:       _Predator_Markets_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Securities",
			Handler:       _Predator_Securities_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Records",
			Handler:       _Predator_Records_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "github.com/Hunsin/compass/trade/pb/APIs.proto",
}

func init() { proto.RegisterFile("github.com/Hunsin/compass/trade/pb/APIs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0x49, 0x5a, 0x92, 0x74, 0xde, 0xd7, 0x3f, 0xcc, 0x41, 0x6a, 0xbc, 0x68, 0x55, 0x10,
	0x8a, 0x49, 0xa8, 0x9f, 0x40, 0x5a, 0x44, 0x0f, 0x4a, 0xad, 0x1f, 0x40, 0x36, 0xd9, 0xb1, 0x2e,
	0x6e, 0xb2, 0x61, 0x77, 0x83, 0xe4, 0xee, 0x07, 0x97, 0x24, 0x8b, 0xd4, 0x93, 0x97, 0x30, 0xf3,
	0x3c, 0xbf, 0x27, 0x33, 0xcc, 0xc2, 0xf5, 0x56, 0xd8, 0xf7, 0x26, 0x4f, 0x0a, 0x55, 0xa6, 0xf7,
	0x4d, 0x65, 0x44, 0x95, 0x16, 0xaa, 0xac, 0x99, 0x31, 0xa9, 0xd5, 0x8c, 0x53, 0x5a, 0xe7, 0xe9,
	0xed, 0xfa, 0xc1, 0x24, 0xb5, 0x56, 0x56, 0xa1, 0x5f, 0xe7, 0xf1, 0xfc, 0xaf, 0x48, 0xff, 0x1d,
	0x02, 0x33, 0x09, 0xc1, 0x9d, 0x90, 0x96, 0x34, 0x1e, 0x41, 0x60, 0xda, 0x32, 0x57, 0x72, 0xea,
	0x9d, 0x7a, 0x57, 0x93, 0x8d, 0xeb, 0xf0, 0x04, 0x26, 0x6f, 0x5a, 0x95, 0xaf, 0x9c, 0x59, 0x9a,
	0xfa, 0xbd, 0x15, 0x75, 0xc2, 0x8a, 0x59, 0xc2, 0x63, 0x88, 0xa8, 0xe2, 0x83, 0x37, 0xea, 0xbd,
	0x90, 0x2a, 0xde, 0x5b, 0x08, 0x63, 0xdb, 0xd6, 0x34, 0x1d, 0xf7, 0x72, 0x5f, 0xcf, 0xe6, 0x10,
	0x2e, 0x35, 0xfb, 0x94, 0xa4, 0x71, 0x1f, 0x7c, 0xc1, 0xdd, 0x28, 0x5f, 0x70, 0x3c, 0x84, 0x51,
	0xa3, 0xa5, 0x1b, 0xd0, 0x95, 0xb3, 0x00, 0xc6, 0x4f, 0x8d, 0x94, 0x8b, 0x67, 0x08, 0x97, 0xc3,
	0xfe, 0x78, 0x06, 0xd1, 0x86, 0xb6, 0xc2, 0x74, 0xfb, 0xfe, 0x4b, 0xea, 0x3c, 0x71, 0x7f, 0x8b,
	0xa3, 0xae, 0xe9, 0x68, 0x3c, 0x87, 0xc8, 0x89, 0x06, 0x7f, 0xd4, 0x78, 0x17, 0xce, 0xbc, 0xc5,
	0x97, 0x07, 0xd1, 0x5a, 0x13, 0x67, 0x56, 0x69, 0xbc, 0x80, 0xf0, 0x91, 0xe9, 0x0f, 0xb2, 0xbb,
	0x81, 0xbd, 0x64, 0xb8, 0xd2, 0xe0, 0x64, 0x1e, 0xce, 0x01, 0x5e, 0xa8, 0x68, 0xb4, 0xb0, 0x82,
	0x0c, 0x42, 0x07, 0x0e, 0x87, 0x8b, 0x0f, 0x1c, 0xea, 0xec, 0x36, 0xf3, 0xf0, 0x12, 0xc2, 0x0d,
	0x15, 0x4a, 0xf3, 0xdf, 0xe4, 0x7f, 0x47, 0xae, 0x98, 0x90, 0x6d, 0xe6, 0xe5, 0x41, 0xff, 0x06,
	0x37, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x52, 0xef, 0x89, 0xdc, 0xe5, 0x01, 0x00, 0x00,
}
